export const Projects = [
    {
        id: 170,
        title: 'My Web Portfolio',
        subtitle: 'My web portfolio',
        subheader: 'June, 2021',
        image: '/images/portfolio.jpg',
        description: 'A React NextJs that shows my web version of my portfolio',
        languages: ['NextJs', 'ReactJs', 'Js', 'Sass'],
        link: '',
    },
    {
        id: 160,
        title: 'UI Screen Designs',
        subtitle: 'UI design',
        subheader: 'May, 2021',
        image: '/images/ui-build.jpg',
        description: 'A Project that contain different UI Project Screens',
        languages: ['ReactJs', 'Js', 'Sass'],
        link: '',
    },
    {
        id: 140,
        title: 'BlueCube App',
        subtitle: 'BlueCube App',
        subheader: 'Apr, 2021',
        image: '/images/blueapp.jpg',
        description: 'Integrated using Vuex to Unsplash API for photos display',
        languages: ['VueJs', 'NuxtJs', 'Sass'],
        link: '',
    },
    {
        id: 150,
        title: 'Covid Data',
        subtitle: 'Covid Data',
        subheader: 'Feb, 2021',
        image: '/images/covid.jpg',
        description: 'A Dashboard that display updated Covid Data',
        languages: ['React', 'Redux', 'Sass', 'Js'],
        link: '',
    },
    {
        id: 120,
        title: 'Versa NG',
        subtitle: 'Versa NG',
        subheader: 'Sept, 2019',
        image: '/images/versa.jpg',
        description: 'An Investment Web Application',
        languages: ['Java', 'Angular', 'Sass', 'Js'],
        link: '',
    },
    {
        id: 130,
        title: 'Switfly Global',
        subtitle: 'Switfly Global',
        subheader: 'Apr, 2017',
        image: '/images/swiftly.jpg',
        description: 'A Shippment Web Application (Collaborated)',
        languages: ['Php', 'MySQL', 'jQuery', 'Sass', 'Js'],
        link: '',
    },
    {
        id: 100,
        title: 'Nigerian Women TechSters',
        subtitle: 'NWT',
        subheader: 'May, 2017',
        image: '/images/nwt-bg.5cdb0474.png',
        description: 'The frontend and also backend development',
        languages: ['Php', 'MySQL', 'jQuery', 'Sass', 'Js'],
        link: '',
    },
    {
        id: 110,
        title: 'Seed Dev',
        subtitle: 'seeddev',
        subheader: 'May, 2017',
        image: '/images/seeddev.jpg',
        description: 'The frontend and also backend development',
        languages: ['Php', 'MySQL', 'jQuery', 'Sass', 'Js'],
        link: '',
    },
];

export const ShortProjects = [
    {
        id: 170,
        title: 'My Web Portfolio',
        subtitle: 'My web portfolio',
        subheader: 'June, 2021',
        image: '/images/portfolio.jpg',
        description: 'A React NextJs that shows my web version of my portfolio',
        languages: ['NextJs', 'ReactJs', 'Js', 'Sass'],
        link: '',
    },
    {
        id: 160,
        title: 'UI Screen Designs',
        subtitle: 'UI design',
        subheader: 'May, 2021',
        image: '/images/ui-build.jpg',
        description: 'A Project that contain different UI Project Screens',
        languages: ['ReactJs', 'Js', 'Sass'],
        link: '',
    },
    {
        id: 140,
        title: 'BlueCube App',
        subtitle: 'BlueCube App',
        subheader: 'Apr, 2021',
        image: '/images/blueapp.jpg',
        description: 'Integrated using Vuex to Unsplash API for photos display',
        languages: ['VueJs', 'NuxtJs', 'Sass'],
        link: '',
    },
    // {
    //     id: 150,
    //     title: 'Covid Data',
    //     subtitle: 'Covid Data',
    //     subheader: 'Feb, 2021',
    //     image: '/images/covid.jpg',
    //     description: 'A Dashboard that display updated Covid Data',
    //     languages: ['React', 'Redux', 'Sass', 'Js'],
    // },
];

// export const Projects = [];

export const EducationList = [
    {
        id: '1',
        schoolName: 'Federal Univrsity of Technology, Akure',
        location: 'Akure.',
        country: 'Nigeria',
        courseName: 'Computer Science',
        yearRange: '2010 - 2015',
        certificateEarn: 'Bachelor of Technology (B.Tech)',
    },
    {
        id: '2',
        schoolName: 'NEST School of Technology',
        location: 'Akure.',
        country: 'Nigeria',
        courseName: '',
        yearRange: 'April 2017 - May 2018',
        certificateEarn: 'DevCRIB Prolificate Software Engineer',
    },
    {
        id: '3',
        schoolName: 'Chartered Institute of Risk and Loan Management of Nigeria',
        location: 'Ilorin.',
        country: 'Nigeria',
        courseName: '',
        yearRange: '2016 - 2017',
        certificateEarn: 'Graduate Member, GCIRLMN',
    },
    {
        id: '4',
        schoolName: 'React JS Certification',
        location: 'Udemy.',
        country: 'Udemy',
        courseName: '',
        yearRange: '2018 - 2019',
        certificateEarn: 'REACTJS',
    },
    // {
    //     id: '2',
    //     schoolName: 'Government Science College, Iyin',
    //     location: 'Iyin.',
    //     country: 'Nigeria',
    //     courseName: '',
    //     yearRange: '2010 - 2015',
    //     certificateEarn: 'Senior Secondary School Certificate (SSCE)',
    // },
];

// export const EducationList = [];

// mpn i aos --save
